# Generated by Django 2.2.10 on 2022-03-24 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parser_app', '0011_auto_20191022_1356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='college_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='education',
        ),
    ]
